import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 sticky top-0 bg-white z-20">
          <div className="flex items-center justify-between ">
            <Link href="/">
              <h1 className="text-xl font-bold text-[#000b58] cursor-pointer">
                Next Movie App
              </h1>
            </Link>
            <nav className="hidden md:block">
              <ul className="flex space-x-4 text-[#000b58] text-[18px]">
                <li>
                  <Link href="/movies">Movies</Link>
                </li>
                <li>
                  <Link href="/about">About</Link>
                </li>
                <li>
                  <Link href="/contact">Contact</Link>
                </li>
              </ul>
            </nav>
            <div className="flex space-x-4">
              <button className="px-4 py-2 bg-linear-to-r from-[#000b58] to-purple-700 text-white rounded">
                Login
              </button>
              <button className="px-4 py-2 bg-linear-to-r from-[#000b58] to-purple-700 text-white rounded">
                Sign Up
              </button>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
